version: "3"
services:
  develop:
    build: .
    ports:
      - "3500:3500"
    container_name: gfw-mail-api-develop
    environment:
      PORT: 3500
      NODE_PATH: app/src
      NODE_ENV: dev
      LOGGER_LEVEL: debug
      SUPPRESS_NO_CONFIG_WARNING: "true"
      API_GATEWAY_URL: http://192.168.99.100:8000
      QUEUE_URL: redis://192.168.99.100:6379
      QUEUE_PROVIDER: redis
      QUEUE_NAME: mail
      SPARKPOST_API_KEY: notset
    volumes:
      - ./app:/opt/gfw-mail-api/app
    command: node node_modules/.bin/grunt --gruntfile app/Gruntfile.js
