version: "3"
services:
  develop:
    build: .
    ports:
      - "3500:3500"
    container_name: gfw-mail-api-develop
    environment:
      PORT: 3500
      NODE_PATH: app/src
      NODE_ENV: dev
      LOGGER_LEVEL: debug
      SUPPRESS_NO_CONFIG_WARNING: "true"
      API_GATEWAY_URL: http://192.168.99.100:8000
      QUEUE_URL: redis://redis
      QUEUE_PROVIDER: redis
      QUEUE_NAME: mail
      SPARKPOST_API_KEY: notset
    volumes:
      - ./app:/opt/gfw-mail-api/app
    depends_on:
      - redis
      - mongo
    command: node node_modules/.bin/grunt --gruntfile app/Gruntfile.js

  redis:
    image: redis
    expose:
      - 6379

  # mongo:
  #   image: mongo:3.4
  #   container_name: mail-mongo-test
  #   command: --smallfiles
  #   ports:
  #     - "27017"
  #   volumes:
  #     - $HOME/docker/data/dataset:/data/db