version: "3"
services:
  develop:
    build: .
    ports:
      - "3500:3500"
    container_name: gfw-mail-api-develop
    environment:
      PORT: 3500
      NODE_ENV: dev
      LOGGER_LEVEL: debug
      SUPPRESS_NO_CONFIG_WARNING: "true"
      API_GATEWAY_URL: http://192.168.99.100:8000
      QUEUE_URL: redis://redis
      QUEUE_PROVIDER: redis
      QUEUE_NAME: mail
      SPARKPOST_API_KEY: notset
    volumes:
      - ./app:/opt/gfw-mail-api/app
      - ./nodemon.json:/opt/gfw-mail-api/nodemon.json
    depends_on:
      - redis
    command: yarn dev

  test:
    build: .
    container_name: gfw-mail-api-test
    environment:
      PORT: 3500
      NODE_ENV: test
      LOGGER_LEVEL: debug
      SUPPRESS_NO_CONFIG_WARNING: "true"
      SPARKPOST_API_KEY: foobar
      MONGO_PORT_27017_TCP_ADDR: mongo
      QUEUE_NAME: mail_test
      QUEUE_PROVIDER: redis
      QUEUE_URL: redis://redis
    volumes:
      - ./app:/opt/gfw-mail-api/app
      - ./nodemon.json:/opt/gfw-mail-api/nodemon.json
      - ./jest.config.js:/opt/gfw-mail-api/jest.config.js
    command: yarn test
    depends_on:
      - redis

  redis:
    image: redis
    expose:
      - 6379